### ISSUE TITLE
Error when decrypting.

### ISSUE THREAD

**Issue by madtechsupport** [pcarrier/gauth#2]
Hi,

I'm getting the following error when decrypting:
```
gauth
Encryption password:
panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
	/Users/warren/Go/src/github.com/pcarrier/gauth/gauth.go:106 +0x8d8

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 34 [select, locked to thread]:
runtime.gopark(0x1a2390, 0xc8200bc728, 0x164fd0, 0x6, 0x2c818, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc8200bc728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc8200bc728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

I'm using the following versions:
```
go version
go version go1.5.1 darwin/amd64
openssl version
OpenSSL 0.9.8zg 14 July 2015
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1021
```

Any thoughts?

**Comment by pcarrier** [comment]
Oops yes. Your file has exactly 0 padding, which is a case I don't handle correctly. Will work on a fix ASAP.

**Comment by pcarrier** [comment]
Thanks for the report, sorry for the delay! Should be fixed in master in minutes.
